site_name: ClipTale
repo_url: https://github.com/WSQsGithub/ClipTale
site_url: https://WSQsGithub.github.io/ClipTale
site_description: This is the repo for ClipTale, a desktop app that helps video content makers manage their clips more easily.
site_author: Siqi Wang
edit_uri: edit/main/docs/
repo_name: WSQsGithub/ClipTale
copyright: Maintained by <a href="https://WSQsGithub.com">WSQsGithub</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/cliptale"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WSQsGithub/ClipTale
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ClipTale

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
